name: firebase_firestore
description: A starting point for Dart libraries or applications.
version: 0.0.1+1
author: long1eu <home@long.1eu>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  firebase_common:
     git:
       url: https://github.com/dmytroSolidSoftware/firebase_dart_sdk.git
       path: firebase_common

  firebase_database_collection:
    git:
      url: https://github.com/dmytroSolidSoftware/firebase_dart_sdk.git
      path: firebase_database_collection

  protobuf: ^1.0.1
  grpc: ^2.1.3
  rxdart: ^0.22.2


  firebase_internal:
    git:
      url: https://github.com/dmytroSolidSoftware/firebase_dart_sdk.git
      path: firebase_internal

dev_dependencies:
  test: ^1.6.8
  mockito: ^4.1.0
  moor_ffi: ^0.2.0
  uuid: ^2.0.0