name: firebase_storage
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/fluttercommunity/firebase_flutter_sdk
author: long1eu <home@long1.eu>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  isolate: ^2.0.2
  rxdart: ^0.22.2
  googleapis: 0.52.0
  firebase_common:
    git:
      url: https://github.com/dmytroSolidSoftware/firebase_dart_sdk.git
      path: firebase_common

dev_dependencies:
  test: ^1.6.8
  mockito: ^4.1.0
